# .streamlit/config.toml
[theme]
# Base: Tema Claro (Light)
base="light" 
# Fondo Principal: Blanco puro
backgroundColor="#FFFFFF" 
# Fondo Secundario: Gris muy claro para la barra lateral (Filtros)
secondaryBackgroundColor="#F0F0F0" 
# Color Primario: El Verde Corporativo de Greif
primaryColor="#005C3B" 
# Color del Texto: Gris carb√≥n oscuro para alta legibilidad
textColor="#333333"
