[theme]
base="light" 
backgroundColor="#F7FAFC"          # Blanco suave
secondaryBackgroundColor="#E4E7EB" # Gris muy claro para la barra lateral
primaryColor="#3182CE"             # Mismo azul profesional
textColor="#2D3748"                # Texto gris oscuro
